# Generated by Django 4.2.29 on 2026-03-05 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('company_id', 'Company ID'), ('drivers_license', "Driver's License")], max_length=20)),
                ('document_url', models.FileField(upload_to='identity_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Identity Document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='providerprofile',
            options={'verbose_name': 'Provider Profile'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='completion_rate',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='coverage_radius_km',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='fixed_rate',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='id_document_url',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='loyalty_tier',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='pricing_model',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='response_rate',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='selfie_url',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='subcategory_id',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='total_jobs_completed',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='wallet_balance',
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='total_jobs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_on_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
