# Generated by Django 4.2.29 on 2026-03-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='role',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('provider', 'Service Provider'), ('admin', 'Admin')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
