# Generated by Django 4.2.29 on 2026-03-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phoneotp_first_name_phoneotp_last_name_phoneotp_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='auto_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='biometric_selfie',
            field=models.FileField(blank=True, help_text='Liveness selfie photo submitted by the provider during onboarding.', null=True, upload_to='biometric_selfies/'),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='ocr_confidence',
            field=models.FloatField(blank=True, help_text='OCR match confidence score (0.0–1.0). Set by automated verification task.', null=True),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='ocr_extracted',
            field=models.JSONField(blank=True, help_text='Raw fields extracted by OCR (name, DOB, ID number) for audit purposes.', null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum service price in ETB.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum service price in ETB.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='biometric_score',
            field=models.FloatField(blank=True, help_text='Liveness/face-match confidence score (0.0–1.0). Set by automated check.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='biometric_verified',
            field=models.BooleanField(default=False),
        ),
    ]
