# Generated by Django 4.2.29 on 2026-03-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_identitydocument_auto_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged – Needs Review')], default='pending', max_length=10),
        ),
    ]
