# Generated by Django 4.2.29 on 2026-03-17 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_identitydocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='extracted_dob',
            field=models.DateField(blank=True, help_text='Date of birth from OCR.', null=True),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='extracted_expiry',
            field=models.DateField(blank=True, help_text='Document expiry date from OCR.', null=True),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='extracted_id_number',
            field=models.CharField(blank=True, db_index=True, help_text='ID number extracted by OCR. Indexed for deduplication.', max_length=128),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='extracted_name',
            field=models.CharField(blank=True, help_text='Name extracted by OCR.', max_length=255),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='extracted_nationality',
            field=models.CharField(blank=True, help_text='Nationality from OCR.', max_length=100),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='ocr_language',
            field=models.CharField(blank=True, choices=[('am', 'Amharic'), ('en', 'English'), ('auto', 'Auto-detect')], help_text='Language detected by OCR engine.', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='FaceBiometricVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfie_image', models.FileField(upload_to='face_verification/')),
                ('liveness_score', models.FloatField(help_text='Liveness check score (0.0–1.0).')),
                ('face_match_score', models.FloatField(help_text='Face comparison score (0.0–1.0): selfie vs ID photo.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged – Needs Review'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('auto_verified', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_verification', to='accounts.identitydocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_face_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Biometric Verification',
                'ordering': ['-created_at'],
            },
        ),
    ]
