# Generated by Django 4.2.29 on 2026-03-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_identitydocument_extracted_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='current_latitude',
            field=models.FloatField(blank=True, help_text='Current GPS latitude (updated when online).', null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='current_longitude',
            field=models.FloatField(blank=True, help_text='Current GPS longitude (updated when online).', null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='is_online',
            field=models.BooleanField(default=False, help_text='True when provider is actively accepting jobs.'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last location update.', null=True),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Service area description (e.g., "Addis Ababa")', max_length=255),
        ),
    ]
