# Generated by Django 4.2.29 on 2026-03-17 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_providerprofile_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True, help_text='URL to category icon')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('register', 'Signup Registration'), ('login', 'Login'), ('provider_onboarding', 'Provider Onboarding')], max_length=20),
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='accounts.servicecategory')),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_service', models.ForeignKey(help_text='Primary service category (the one they specialize in)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.servicecategory')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_offering', to='accounts.providerprofile')),
                ('subservices', models.ManyToManyField(help_text='Sub-services provider offers (can be multiple)', to='accounts.subservice')),
            ],
            options={
                'verbose_name_plural': 'Provider Services',
            },
        ),
        migrations.CreateModel(
            name='ProviderOnboardingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('step', models.PositiveSmallIntegerField(default=1, help_text='Current step (1-5)')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='onboarding_temp/')),
                ('document_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('company_id', 'Company ID'), ('drivers_license', "Driver's License")], max_length=20, null=True)),
                ('image_quality', models.FloatField(blank=True, help_text='Image quality score (0-1): detects blurriness, lighting issues', null=True)),
                ('quality_warnings', models.JSONField(blank=True, default=list, help_text='List of quality issues: ["blurry", "poor_lighting", "partial_text"]')),
                ('extracted_data', models.JSONField(blank=True, help_text='OCR extracted fields: {name, phone, id_number, dob, nationality}', null=True)),
                ('ocr_confidence', models.FloatField(blank=True, help_text='Overall OCR confidence (0-1)', null=True)),
                ('confirmed_data', models.JSONField(blank=True, help_text='User-confirmed data after reviewing OCR extraction', null=True)),
                ('phone_for_verification', models.CharField(blank=True, help_text='Phone number to send OTP (extracted or manually entered)', max_length=30, null=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('selfie_file', models.FileField(blank=True, null=True, upload_to='onboarding_temp/')),
                ('liveness_score', models.FloatField(blank=True, null=True)),
                ('face_match_score', models.FloatField(blank=True, null=True)),
                ('face_verified', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_ids', models.JSONField(blank=True, default=list, help_text='IDs of selected sub-services (multiple allowed)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Session expires after 12 hours')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('service_category', models.ForeignKey(blank=True, help_text='Primary service category (1 only)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.servicecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
