# Generated by Django 4.2.29 on 2026-03-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_servicecategory_alter_phoneotp_purpose_subservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOnboardingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('phone_number', models.CharField(db_index=True, max_length=30)),
                ('phone_verified', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='client_onboarding_temp/')),
                ('document_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('company_id', 'Company ID'), ('drivers_license', "Driver's License")], max_length=20, null=True)),
                ('extracted_data', models.JSONField(blank=True, help_text='OCR extracted fields: {name, phone, address, id_number}', null=True)),
                ('ocr_confidence', models.FloatField(blank=True, help_text='OCR confidence (0-1)', null=True)),
                ('image_quality', models.FloatField(blank=True, help_text='Image quality (0-1)', null=True)),
                ('quality_warnings', models.JSONField(blank=True, default=list, help_text='Quality issues: ["blurry", "poor_lighting", "partial_text"]')),
                ('first_name', models.CharField(blank=True, help_text='Auto-filled from OCR or manually entered', max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Session expires after 6 hours')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
