# Generated by Django 4.2.29 on 2026-03-29 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_provideronboardingsession_document_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderManualVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_front_image', models.FileField(upload_to='provider_verification/id_front/')),
                ('id_back_image', models.FileField(upload_to='provider_verification/id_back/')),
                ('selfie_image', models.FileField(upload_to='provider_verification/selfie/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(help_text='Service provider who submitted this verification package.', on_delete=django.db.models.deletion.CASCADE, related_name='manual_verifications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_manual_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Manual Verification',
                'verbose_name_plural': 'Provider Manual Verifications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
