# Generated by Django 4.2.29 on 2026-04-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_identitydocument_extracted_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
