# Generated by Django 4.2.29 on 2026-04-15 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_legacy_ocr_biometric_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=20)),
                ('provider_uid', models.CharField(blank=True, max_length=6)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False, help_text='Mark as reviewed after admin checks the user')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this registration')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Registration Notification',
                'verbose_name_plural': 'User Registration Notifications',
                'ordering': ['-registration_time'],
            },
        ),
    ]
