# Generated by Django 4.2.30 on 2026-04-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_move_service_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='price_min',
        ),
    ]

