# Generated by Django 4.2.29 on 2026-04-15 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_user_registration_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_role', models.CharField(choices=[('client', 'Client'), ('provider', 'Service Provider'), ('admin', 'Admin')], max_length=20)),
                ('requested_role', models.CharField(choices=[('client', 'Client'), ('provider', 'Service Provider'), ('admin', 'Admin')], max_length=20)),
                ('reason', models.TextField(help_text="User's reason for requesting role change")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this request')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_role_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting the role change', on_delete=django.db.models.deletion.CASCADE, related_name='role_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Change Request',
                'verbose_name_plural': 'Role Change Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
