# Generated by Django 4.2.29 on 2026-04-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_user_registration_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_provider_role',
            field=models.BooleanField(default=False, help_text='True if user has provider role'),
        ),
        migrations.AddField(
            model_name='user',
            name='provider_onboarding_completed',
            field=models.BooleanField(default=False, help_text='True if provider onboarding is complete'),
        ),
    ]
