# Generated by Django 4.2.29 on 2026-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rolechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='providermanualverification',
            name='admin_hint',
            field=models.TextField(blank=True, help_text='Internal admin hint (not shown to user)'),
        ),
        migrations.AddField(
            model_name='rolechangerequest',
            name='admin_hint',
            field=models.TextField(blank=True, help_text='Internal admin hint (not shown to user)'),
        ),
        migrations.AddField(
            model_name='rolechangerequest',
            name='rejection_message',
            field=models.TextField(blank=True, help_text='AI-generated rejection message shown to user'),
        ),
        migrations.AlterField(
            model_name='providermanualverification',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='AI-generated rejection message shown to user'),
        ),
    ]
