# Generated by Django 4.2.29 on 2026-04-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_fix_providermanualverification_admin_hint_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_client_role',
            field=models.BooleanField(default=True, help_text='True if user has client role (default for all users)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_provider_role',
            field=models.BooleanField(default=False, help_text='True if user has provider role (approved or in progress)'),
        ),
    ]
