# Generated by Django 4.2.29 on 2026-04-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_providermanualverification_admin_hint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_roles',
            field=models.JSONField(default=list, help_text='List of roles this user can switch between'),
        ),
    ]
