# Generated by Django 4.2.30 on 2026-04-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_providerprofile_price_max_and_more'),
        ('accounts', '0021_fix_providermanualverification_admin_hint_default'),
    ]

    operations = [
    ]
