# Generated by Django 4.2.29 on 2026-04-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_available_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available_roles',
        ),
        migrations.AddField(
            model_name='user',
            name='approved_roles',
            field=models.JSONField(default=list, help_text='List of all approved roles for this user (e.g., ["client", "provider"])'),
        ),
    ]
