# Generated by Django 4.2.29 on 2026-04-16 06:31

from django.db import migrations


def populate_approved_roles(apps, schema_editor):
    """
    Populate approved_roles for existing users.
    - Users with approved role change requests get both roles
    - Other users get their current role only
    """
    User = apps.get_model('accounts', 'User')
    RoleChangeRequest = apps.get_model('accounts', 'RoleChangeRequest')
    
    for user in User.objects.all():
        approved_roles = [user.role]
        
        # Check for approved role change requests
        approved_requests = RoleChangeRequest.objects.filter(
            user=user,
            status='approved'
        )
        
        for request in approved_requests:
            # Add both current and requested roles
            if request.current_role not in approved_roles:
                approved_roles.append(request.current_role)
            if request.requested_role not in approved_roles:
                approved_roles.append(request.requested_role)
        
        user.approved_roles = approved_roles
        user.save(update_fields=['approved_roles'])


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear approved_roles"""
    User = apps.get_model('accounts', 'User')
    User.objects.all().update(approved_roles=[])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_add_approved_roles'),
    ]

    operations = [
        migrations.RunPython(populate_approved_roles, reverse_populate),
    ]
