# Generated by Django 4.2.30 on 2026-04-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_merge_20260422_2258'),
        ('accounts', '0023_set_has_provider_role_for_existing_providers'),
    ]

    operations = [
    ]
