# Generated by Django 4.2.30 on 2026-05-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_providerprofile_free_jobs_remaining'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subservice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProviderService',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='SubService',
        ),
    ]
