# Generated by Django 4.2.30 on 2026-05-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_subservice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='free_jobs_remaining',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
