# Generated by Django 4.2.30 on 2026-04-18 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_commissionpayment_commission_rule'),
        ('services', '0002_service_catalog_move'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommissionRule',
        ),
    ]
