# Generated by Django 4.2.30 on 2026-06-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_servicecategory_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='name_am',
            field=models.CharField(blank=True, help_text='Amharic name for this category', max_length=100),
        ),
        migrations.AddField(
            model_name='subservice',
            name='name_am',
            field=models.CharField(blank=True, help_text='Amharic name for this sub-service', max_length=100),
        ),
    ]
