# Generated by Django 4.2.29 on 2026-03-05 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('services', '0001_initial'),
        ('accounts', '0002_identitydocument_alter_providerprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('telebirr', 'TeleBirr'), ('chapa', 'Chapa')], default='telebirr', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('transaction_ref', models.CharField(max_length=255, unique=True)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('failure_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='services.commissionrule')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_payments', to='orders.order')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_payments', to='accounts.providerprofile')),
            ],
            options={
                'verbose_name': 'Commission Payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
