# Generated by Django 4.2.30 on 2026-04-18 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionpayment',
            name='commission_rule',
        ),
    ]
